### ISSUE TITLE
FYI restore is a console command only!

### ISSUE THREAD

**Issue by Bucky420** [FTBTeam/FTB-StoneBlock-Companion#4]
if you run in game you will get 
`Could not parse command: Cannot invoke "net.minecraft.server.MinecraftServer.m_129880_(net.minecraft.resources.ResourceKey)" because the return value of "net.minecraftforge.server.ServerLifecycleHooks.getCurrentServer()" is null`

this is for informal purposes

**Comment by MichaelHillcox** [comment]
Update to the latest version
